name: Build and Deploy to AWS

on:
  push:
    branches:
      - main  # Runs on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 3️⃣ Build the Docker Image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flaskenc:latest .

      # 4️⃣ Push the Image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flaskenc:latest

      # 5️⃣ Deploy to AWS EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAxt51UqHh5KgHuwYwTRo7ExC4mgHukKtPp1axjvH7u3ojAbHk
            5dQsYNl68lhEKORdBRh3JhArwhO0J4IJW027TPv5ZAhleWFyoyy4nmO68PJ2mTL2
            wpEhyA8c8PJnzB/TvwikMbvcRJokO18k7ReGIWdEHaE1U3z2GGws50DNCMhzIkQU
            mWpGKvB/BTmiPX+R7sgH+6OqZI1d5ekXGVdLHX4sop0ID9ykKUTHGhooHyzJot98
            Tgh3wKAiRvN5z5HaFsV0ZMQQFs0ZG/tEN7iKurM7qRGPlUane7QFCm2zBatbnMyR
            C0QVul5XD8MHhHI2OHqhNYLNaiVJ6taIL+IYZwIDAQABAoIBABeh3/dN3XY6sZB8
            D8lZ0KNXXViP2jW+5dxQ5RDDmNKSlQ5igXz+Vbe8oGukKZVibdtpKN+RFGIfzUzU
            myAKgLOJTf2hMc3W0rSpX9cSquhvJ8DU2ZYNgSIxCZNoewU60wLkl/6BAI/2cU/M
            4qp6HSpjBykuOxQMyYHleQCSJstgMOM0U6nRvKKZuC9dgelI4oh4E2P0AxCUEAEj
            k/p4uGBvQQPuc4BQYHcqFYcfog2LT60sXdJZVRXeIbvKLqL/2Es3Xp4uNX6f8aqa
            udfqJ54exWY0PHmd70KfLEVzmBn6rorI7nNEqqDHadJ7IIBWWAQjInjxB7jnC53C
            BeMUiWECgYEA9CtIDc0VcFCYu0/xAK7fkYAk7NWqTJhubRG/EpIhqy1zeGRVK7y5
            vMJSO2hB3BiXxIgBUEtC6MMZRXX6I1QZ4jTDAoRksi8uAgMF+cU5/lc5ApFJNzDq
            XNZbFExL3xz0cRzyX0dq6v3DzQaENHUoPv+TlRpG/apDRtvnKXROtzUCgYEA0IFE
            HgAXFqnhEvUhJNF1aCD5wkOT5IykgnlSemb5DF/QzaWDcRL52u0b8MQ27VF7vB1/
            AqKvOY1D0ZO0feOFzCEiEn/V+fMDZzgbaBNuZCU08lKAmSckHnLosG0kaApIc7iK
            FG/9hpjF1/Gtsv7ChnVpydX1Lr/KuN/w9aP12KsCgYEAzmyg9/oAO/oHhaRqDbfK
            DwqVLRzeYu8jvFYagarFiCBe1NOOJfHh3TEzsEHOHDM2a9LHuYhHQt1eShkZpjB9
            yX3tt/0R3IqCjPTdYnJZOyumaQNHML/MAzy9t4VhR3kFN3PPfLm2LIDpvjXaIzdB
            FTGhJZcXmXEOe6OB5MwNmFkCgYAHeSqk3KH3OP2NPWYDuNI5ej0ZfmyVm4jl+E1B
            f+FbVS/Zvx339pMoCqmetpm1Zd9GfdQolwYqzOpqX53viTEpgOKEwTo9LD2p/HPX
            BiNFyaOdL+HWG3YK9VlrwW21oPC53Rpt4xm2MlGdDNeJ++GjCiBRkK6qD0vH1pb/
            ZvIP4wKBgQDdx5S190ILB0dfcFdp1B0etFj3FF5KceAhRc8beD4o1zksmoeBgzZo
            juw91DNZNFARd6H8WKhGNQAkucxTi+hVayvAEyXqPhOJcY871GZiw19OdT7J/YCU
            AdwneApNdvi0/TSlhEb1moSZ7uFNamNaUiwozRgcjiuQ549GpPiS6g==
            -----END RSA PRIVATE KEY-----

          port: 22  # Ensure this is set
          script: |
            whoami  # Test if the connection works
            docker stop flaskenc || true
            docker rm flaskenc || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/flaskenc:latest
            docker run -d --name flaskenc -p 5001:5001 ${{ secrets.DOCKER_HUB_USERNAME }}/flaskenc:latest

